version: '3.9'
services:
  rabbitmq:
    image: "rabbitmq:3.12-management"
    ports:
      - "5672:5672" # порт для AMQP
      - "15672:15672" # порт для веб-панели управления

  postgres:
    image: "postgres:latest"
    ports:
      - "5432:5432" # порт PostgreSQL
    environment:
      POSTGRES_USER: Kamil
      POSTGRES_PASSWORD: "12345"
      POSTGRES_DB: f_base

  python-app:
    build: ./Python-app
    depends_on:
      - rabbitmq
      - postgres
    environment:
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: "5672"
      RABBITMQ_USER: guest
      RABBITMQ_PASSWORD: guest
      POSTGRES_HOST: postgres
      POSTGRES_PORT: "5431"
      POSTGRES_USER: user
      POSTGRES_PASSWORD: "12345"
      POSTGRES_DB: f_base
