version: '3.9'

networks:
  mynetwork:
    driver: bridge

services:
  postgres:
    build: ./Postgres
    ports:
      - '5432:5432'
    networks:
      - mynetwork

  rabbit:
    image: rabbitmq:3.12-management
    ports:
      - '5672:5672'
      - '15672:15672'
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    networks:
      - mynetwork

  app:
    build: ./Python-app
    depends_on:
      - postgres
      - rabbit
    networks:
      - mynetwork
